add contents to Index and applied styles
sediqullahbadakhsh/badakhsh-portfolio pull request #1
Opened 2022-01-06 21:31 UTC by sediqullahbadakhsh

added two sections : 
1- Navbar
2- little information with an image
applied css flexbox to it.

2022-01-06 23:06 UTC, VICTOR-CHUKWU requested changes
Hi @sediqullahbadakhsh  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- [ ] Add a screenshot to show how your website looks like, after the project description.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 23:06 UTC, VICTOR-CHUKWU commented on index.html
>  </body>
- [ ] @sediqullahbadakhsh You did well but I think it will be good to stick to the figma design as your mobile view is currently no like the original design.
 your design 👇 
                  
![image](https://user-images.githubusercontent.com/66097371/148462604-d53cdc56-243d-4eb0-9899-8d74d4593786.png)
Figma design 👇 
                    
![image](https://user-images.githubusercontent.com/66097371/148462732-ac92397e-e3a2-4ed7-981f-2641fd7b6f7e.png)
you can check the Figma design by clicking this [link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)

2022-01-06 23:06 UTC, VICTOR-CHUKWU commented on index.html
> +            </ul>
- [ ] As we are still in the mobile version of this project, your `header` should look like this  
![image](https://user-images.githubusercontent.com/66097371/148463244-7b461b14-941c-4aac-b2eb-d5a70cffa1bd.png)
You might do well to hide the `<ul></ul>` with CSS `display: none` or replace it with a hamburger menu as shown in the design

2022-01-06 23:06 UTC, VICTOR-CHUKWU commented on index.html
> +                <h1>I am Sediqullah Badakhsh</h1>
- [ ] Please, it would be better to use only one `h1` for the heading, so the code should be `<h1>Hey there. I am Sediqullah Badakhsh</h1>`  . It is always a good practice to have one and only one h1 element on a web page.

2022-01-07 14:16 UTC, ReshyResh approved these changes
# Hi @sediqullahbadakhsh , 
### You did a great job implementing the changes requested by the previous reviewer!
#### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-07 14:41 UTC, merged

2022-01-07 14:41 UTC, sediqullahbadakhsh commented
Thank you.