Project modal
sediqullahbadakhsh/badakhsh-portfolio pull request #11
Opened 2022-01-27 11:23 UTC by sediqullahbadakhsh

With respect to the Figma Template the following functionality added to Project section (not all cards):
1- created modal section within html (there are 2 but It was for expermenting for all cards which I am working on it and I guess it is not part of the requirements :).
2- add styles for the Mobile first
3- created responsivness for both Tablet and Desktop something similar to Figma.
4- applied Popup functionality using JavaScript.
5- add close btn funtionality to the modal.
Thanks

2022-01-27 11:35 UTC, ShoiraTa requested changes
Hi team,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 11:35 UTC, ShoiraTa commented on index.html
> +                  </button>
- [ ] Please add icons on buttons as provided in Figma:

Figma  | Yours
------------- | -------------
![image](https://user-images.githubusercontent.com/77038610/151350712-78ce5fd2-98b6-4803-bfd3-dbbbe6159712.png) | ![image](https://user-images.githubusercontent.com/77038610/151350653-f7689bba-fa45-4fff-b8a5-a85e8ceac7cb.png)

2022-01-27 11:35 UTC, ShoiraTa commented on index.html
> +              </p>
- [ ] Please set the typography style as provided in Figma, you can check the corresponding styles on the right side menu:

![image](https://user-images.githubusercontent.com/77038610/151350894-7881c69a-be91-461c-b79f-c9d116490166.png)
You would have to change line height, font color etc.

2022-01-27 11:35 UTC, ShoiraTa commented on app.js
> +
- [ ] Based on project requirements, you should have a JS object with all the project data that populates the popup modal:

![image](https://user-images.githubusercontent.com/77038610/151344337-75e41966-a72f-46d6-94be-809f2e0bb9ec.png)
 
Please add the JS object with project data.

2022-01-28 18:25 UTC, t-yanick approved these changes
Hi @sediqullahbadakhsh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-28 18:59 UTC, merged